name: Publish to Crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo login ${CARGO_REGISTRY_TOKEN} && cargo publish -p reown-relay-rpc --token ${CARGO_REGISTRY_TOKEN} && cargo publish -p reown-relay-client --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_TERM_COLOR: always

